### PR TITLE
Big updates

### PR DESCRIPTION
**Pull request by bleleve**
Hello,

This PR contains contains several updates as well as all previous PR not yet merged from **ecolowtech** :

- update cert-manager to 1.5.4
- update k8s API version to 0.22.2
- migrate to new LiveDNS API (https://api.gandi.net)
- add Helm repo with GitHub pages
- simplify Dockerfile & switch to Buildx
- update make test target (remove shell script)
- update README.md with changes made
- update GitHub workflow with Buildx
- add k8s APF support (k8s >= 1.20)
- add Helm chart-releaser in GitHub action

@bwolf You should activate GitHub Pages on an orphan `gh-pages` to activate helm charts, and create a **v0.1.1** release before merging this PR (changes are detected compared to the previous release).

Best regards.

### CODE REVIEW

**Comment by bleleve** [comment]
This PR also add compatibility with new k8s 1.20 feature "API Priority and Fairness"

**Comment by srgvg** [comment]
@bleleve too bad you had to close, but I had a hunch that would happen. Will you publish your version? Not sure what it takes to get here https://github.com/topics/cert-manager-webhook

**Comment by bleleve** [comment]
@srgvg Sorry, I am still working on some improvements with GitHub actions (build, push and Helm release) and I had to delete the source branch or this PR. I will republish it after some tests ;)

**Comment by bleleve** [comment]
@bwolf @srgvg PR reopened with new GitHub workflow (Docker image build and/or Helm chart release)

**Comment by bwolf** [comment]
That looks awesome. Thanks for the PR. @bleleve What do you mean with "activate GitHub Pages on an orphan gh-pages to activate helm charts"? Especially "on an orphan". Do we need another repo for the gh-pages?

**Comment by bleleve** [comment]
@bwolf Hi Marcus. The gh-branch needs to be detached from your repo history, you can create it with this commands:
```
git checkout --orphan gh-pages
git rm -rf .
git commit --allow-empty -m "Init GitHub Pages branch"
git push origin gh-pages
```

**Comment by bwolf** [comment]
I see with "on an orphan" you mean a branch (i.e. not a repo). I've not found the time to review it deeply, but overall it looks solid.

**Comment by bleleve** [comment]
Hi @bwolf and thanks fort the merge. 

I have seen that the GH workflow didn't work. You have manually created the v0.2.0-alpha release which is not the expected behavior. The "base" job checks for updated go & yaml files between the commit attached to the new tag and the previous release (this is why you had to create the first release manually). Once done, the "build" job is executed if go code was updated, and the "release" one if yaml files where too. The GH release is automatically created during the last job.

To fix this, delete the v0.2.0-alpha release and rerun the workflow. You can then modify the text of the release once it is published.

**Pull request merged**
